name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs: 
  build:
    runs-on: Ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line scripts
      run: echo Hello, world!
      
    - name: Run a multi-line script
      run: 
        echo Add other actions to built,
        echo test, and deploy your project.
